
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (1, 'Ny lavkarbodiett!', '2019-09-05 22:08:37', 'Lifestyle', 'https://frisky.no/wp-content/uploads/2019/03/lavkarbo-kosthold.jpg', 1, 1, 'spis mindre sjokolade', 'Siv Jensen', 26);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (2, 'Ny trend!', '2019-09-05 22:08:37', 'Lifestyle', 'null', 2, 0, 'Ikke altid lurt å ikke tenke', 'Eric', 0);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (3, 'Sports still suck!', '2019-09-05 22:08:37', 'Sports', 'null', 2, 0, 'shots fired, lol', 'Gutta på tur', 0);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (4, 'SV vant valget!', '2019-09-05 22:08:37', 'Politics', 'https://smp.vgc.no/v2/images/b62616e0-3dd4-4040-8df3-32729211add1?fit=crop&h=569&w=834&s=b15b8e4b1293d93936c401d316c6ee538e21f0a8', 1, 1, 'Høyre valgkontor brant ned', 'Sinnataggen', 4);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (5, 'War on all fronts!', '2019-09-05 22:08:37', 'Politics', 'http://www.pxleyes.com/blog/wp-content/uploads/top-news/TopNews7.jpg', 2, 1, 'The landing was made this (Monday) morning. The Fourth and Fifth Marine Divisions made this first Marine Operation since the Palaus were invaded last September. [Lieut. Gen. Holland M. Smith, victor over the Japanese on Saipan, was in command of the Marines, The United Press said.]', 'Nostalgikeren', -2);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (6, 'Lol is the new sms language!', '2019-09-05 22:19:47', 'Lifestyle', 'https://miro.medium.com/max/2560/1*5_ncBq1YbkfmEpDmRdHK4A.jpeg', 1, 1, 'yup thats right', 'Hipster Guro', -1);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (7, 'Sports still suck!', '2019-09-07 16:02:12', 'Sports', 'https://www.standardmedia.co.ke/images/sunday/mveojils2qtqxybcb5cfd5a3079a94.jpg', 1, 1, 'hahahahahahahaahahaha', 'Geeken', 11);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (8, 'Crazed clown, roams the streets.', '2019-09-07 16:03:05', 'Lifestyle', 'https://www.artbrands.com/wp-content/uploads/19401D1.png', 1, 1, 'boink boink, says the horn', 'Fobikeren', -5);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (9, 'asdsd', '2019-10-29 14:05:15', 'Lifestyle', 'https://images2.minutemediacdn.com/image/upload/c_crop,h_1193,w_2121,x_0,y_64/f_auto,q_auto,w_1100/v1565279671/shape/mentalfloss/578211-gettyimages-542930526.jpg', 1, 0, 'asdkaspdokpodas', 'Testeren', 0);
INSERT INTO article (article_id, headline, post_date, category, picture, priority, visible, content, author, likes) VALUES (10, 'asdsd', '2019-10-29 14:39:19', 'Lifestyle', 'https://images2.minutemediacdn.com/image/upload/c_crop,h_1193,w_2121,x_0,y_64/f_auto,q_auto,w_1100/v1565279671/shape/mentalfloss/578211-gettyimages-542930526.jpg', 1, 0, 'asdkaspdokpodas', 'Testeren', 0);


INSERT INTO categories (id, category) VALUES (1, 'Politikk');
INSERT INTO categories (id, category) VALUES (2, 'Livsstil');
INSERT INTO categories (id, category) VALUES (3, 'Sport');